version: '3'

services:
  limesurvey: 
    image: rfs23/limesurvey
    ports:
      - "80:80"
    volumes:
      - ./data/upload/:/var/www/limesurvey/upload/
      - ./data/plugins/:/var/www/limesurvey/plugins/
      - ./conf/limesurvey/config.php:/var/www/limesurvey/application/config/config.php
    depends_on:
      - db
    restart: on-failure
    environment:
      LIME_DBHOST: db
      LIME_DBPORT: 5432
      LIME_DBUSER: limesurvey
      LIME_DBPASSWORD: mylime
      LIME_DBNAME: limesurvey
      LIME_ADMINUSER: admin
      LIME_ADMINPASSWORD: admin
      LIME_ADMINEMAIL: myemail@email.com

  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: limesurvey
      POSTGRES_PASSWORD: mylime
      POSTGRES_DB: limesurvey
    volumes:
      - ./data/db/:/var/lib/postgresql/data/
